### ISSUE TITLE
not generate exe file 

### ISSUE THREAD

**Issue by pretech86** [hakanonymos/steal-chrome-password-all-version#2]
thanks for the tool but it not generate exe file so if i want to send this file to another pc it should installed python to run the file

**Comment by hakanonymos** [comment]
no it doesn't need to install python, watch this video

how to install python,dependances ,

https://www.youtube.com/watch?v=EGkzVcd26I8&t=74s

**Comment by pretech86** [comment]
I used kali linux .. is there any problem because i generate the file but windows can't execute it and I didn't get any mail

**Comment by hakanonymos** [comment]
often there are problems if you compile a program with pyinstaller and want to open it in windows.I will add the linux version of the script steal chrome password, the script must work with all systems, just change the location of the chrome

**Comment by pretech86** [comment]
i used it on windows 10 and it give me ,,, failed to execute script

**Comment by hakanonymos** [comment]
What is your version of Chrome ?? i have tested for chrome 81 windows 7 and Chrome 83 windows 10 and works very good, steal cookie and password 

there are any probleme ,

**Comment by pretech86** [comment]
windows 10 and chrome Version 84.0.4147.89 (Official Build) (64-bit) 

i should use gmail only in mail or not ?

**Comment by hakanonymos** [comment]
only Gmail or change smtp mail

**Comment by pretech86** [comment]
I used gmail and enable less secure applications and still get error cant execute the script , please can you check .. my chrome version is the last version and os is windows 10 

Thanks for the great tool

**Comment by hakanonymos** [comment]
there is a youtube tutorial associated with the video, i think you should ask your questions in the demo video. i did not create the executable file under linux and run it under windows, try to watch the video .

https://www.youtube.com/watch?v=EGkzVcd26I8&feature=youtu.be

**Comment by pretech86** [comment]
I did all steps in video and install it on windows 10 and test the output file on windows 10 but still have the problem

**Comment by hakanonymos** [comment]
have you saved any passwords in your chrome browser ??

since version 80 of google chrome a lot of the python scripts in github don't work, this script works fine, i built the cookie steal, microsoft edge password steal, opera, yandex browser from this script, there is  the premium version and you will have help if you have difficulties: reduce the size of the executable file, receive information by discord or telegram 

https://shoppy.gg/product/VrRKRsK

**Comment by pretech86** [comment]
Yea i have passwords in google chrome , should i change the name of the script?

**Comment by pretech86** [comment]
it's working now but i recieved passwords only not the cookies

**Comment by hakanonymos** [comment]
This version dose not inclut the steal cookies only version premium

**Comment by pretech86** [comment]
How much it cost ?
