### ISSUE TITLE
The exe does not work 

### ISSUE THREAD

**Issue by EMRSoftware** [hakanonymos/steal-chrome-password-all-version#4]
**I did everything you write, ı installed local.bat but when ı run my_email.exe it says "failed to execute script my_email" can you help me to solve this issue

Here is the warn-local.txt**

> `
> This file lists modules PyInstaller was not able to find. This does not
> necessarily mean this module is required for running you program. Python and
> Python 3rd-party packages include a lot of conditional or optional modules. For
> example the module 'ntpath' only exists on Windows, whereas the module
> 'posixpath' only exists on Posix systems.
> 
> Types if import:
> * top-level: imported at the top-level - look at these first
> * conditional: imported within an if-statement
> * delayed: imported from within a function
> * optional: imported within a try-except-statement
> 
> IMPORTANT: Do NOT post this list to the issue-tracker. Use it as a basis for
>            yourself tracking down the missing module. Thanks!
> 
> missing module named 'org.python' - imported by copy (optional), setuptools.sandbox (conditional), xml.sax (delayed, conditional)
> missing module named 'win32com.gen_py' - imported by win32com (conditional, optional), c:\program files (x86)\python37-32\lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py (top-level)
> missing module named pwd - imported by posixpath (delayed, conditional), shutil (optional), tarfile (optional), http.server (delayed, optional), webbrowser (delayed), pathlib (delayed, conditional, optional), netrc (delayed, conditional), getpass (delayed), distutils.util (delayed, conditional), distutils.archive_util (optional)
> missing module named urllib.getproxies_environment - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.proxy_bypass_environment - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.proxy_bypass - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.getproxies - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.urlencode - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.unquote_plus - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.quote_plus - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.unquote - imported by urllib (conditional), requests.compat (conditional)
> missing module named urllib.quote - imported by urllib (conditional), requests.compat (conditional)
> missing module named termios - imported by tty (top-level), getpass (optional)
> missing module named _posixsubprocess - imported by subprocess (conditional), multiprocessing.util (delayed)
> missing module named vms_lib - imported by platform (delayed, conditional, optional)
> missing module named 'java.lang' - imported by platform (delayed, optional), xml.sax._exceptions (conditional)
> missing module named java - imported by platform (delayed)
> missing module named _scproxy - imported by urllib.request (conditional)
> missing module named _winreg - imported by platform (delayed, optional), requests.utils (delayed, conditional, optional), pkg_resources._vendor.appdirs (delayed)
> missing module named _frozen_importlib_external - imported by importlib._bootstrap (delayed), importlib (optional), importlib.abc (optional)
> excluded module named _frozen_importlib - imported by importlib (optional), importlib.abc (optional)
> missing module named readline - imported by cmd (delayed, conditional, optional), code (delayed, conditional, optional), pdb (delayed, optional)
> missing module named org - imported by pickle (optional)
> missing module named grp - imported by shutil (optional), tarfile (optional), pathlib (delayed), distutils.archive_util (optional)
> missing module named pyimod03_importers - imported by c:\program files (x86)\python37-32\lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py (top-level)
> missing module named 'pkg_resources.extern.pyparsing' - imported by pkg_resources._vendor.packaging.requirements (top-level), pkg_resources._vendor.packaging.markers (top-level)
> missing module named _uuid - imported by uuid (optional)
> missing module named __builtin__ - imported by pkg_resources._vendor.pyparsing (conditional), setuptools._vendor.pyparsing (conditional)
> missing module named ordereddict - imported by pkg_resources._vendor.pyparsing (optional), setuptools._vendor.pyparsing (optional)
> missing module named StringIO - imported by urllib3.packages.six (conditional), six (conditional), requests.compat (conditional), setuptools._vendor.six (conditional), pkg_resources._vendor.six (conditional)
> missing module named 'com.sun' - imported by pkg_resources._vendor.appdirs (delayed, conditional, optional)
> missing module named com - imported by pkg_resources._vendor.appdirs (delayed)
> missing module named multiprocessing.set_start_method - imported by multiprocessing (top-level), multiprocessing.spawn (top-level)
> missing module named multiprocessing.get_start_method - imported by multiprocessing (top-level), multiprocessing.spawn (top-level)
> missing module named multiprocessing.TimeoutError - imported by multiprocessing (top-level), multiprocessing.pool (top-level)
> missing module named multiprocessing.get_context - imported by multiprocessing (top-level), multiprocessing.pool (top-level), multiprocessing.managers (top-level), multiprocessing.sharedctypes (top-level)
> missing module named multiprocessing.BufferTooShort - imported by multiprocessing (top-level), multiprocessing.connection (top-level)
> missing module named multiprocessing.AuthenticationError - imported by multiprocessing (top-level), multiprocessing.connection (top-level)
> missing module named pkg_resources.extern.packaging - imported by pkg_resources.extern (top-level), pkg_resources (top-level)
> missing module named pkg_resources.extern.appdirs - imported by pkg_resources.extern (top-level), pkg_resources (top-level)
> missing module named 'pkg_resources.extern.six.moves' - imported by pkg_resources (top-level), pkg_resources._vendor.packaging.requirements (top-level)
> missing module named pkg_resources.extern.six - imported by pkg_resources.extern (top-level), pkg_resources (top-level)
> missing module named 'Crypto.Protocol' - imported by C:\Users\emir_\OneDrive\Masaüstü\steal-chrome-password-all-version-master\local.py (delayed)
> missing module named Crypto - imported by C:\Users\emir_\OneDrive\Masaüstü\steal-chrome-password-all-version-master\local.py (delayed)
> missing module named bcrypt - imported by cryptography.hazmat.primitives.serialization.ssh (optional)
> missing module named six.moves.range - imported by six.moves (top-level), cryptography.hazmat.backends.openssl.backend (top-level)
> runtime module named six.moves - imported by cryptography.hazmat.backends.openssl.backend (top-level)
> missing module named cryptography.x509.UnsupportedExtension - imported by cryptography.x509 (optional), urllib3.contrib.pyopenssl (optional)
> missing module named olefile - imported by PIL.MicImagePlugin (top-level), PIL.FpxImagePlugin (top-level)
> missing module named 'PySide2.QtCore' - imported by PIL.ImageQt (conditional, optional)
> missing module named PySide2 - imported by PIL.ImageQt (conditional, optional)
> missing module named 'PyQt5.QtCore' - imported by PIL.ImageQt (conditional, optional)
> missing module named numpy - imported by PIL.ImageFilter (optional), setuptools.msvc (delayed, conditional)
> missing module named dummy_thread - imported by cffi.lock (conditional, optional)
> missing module named thread - imported by cffi.lock (conditional, optional), cffi.cparser (conditional, optional)
> missing module named 'setuptools.extern.pyparsing' - imported by setuptools._vendor.packaging.requirements (top-level), setuptools._vendor.packaging.markers (top-level)
> runtime module named setuptools.extern.six.moves - imported by setuptools.dist (top-level), setuptools.py33compat (top-level), setuptools.command.easy_install (top-level), setuptools.sandbox (top-level), setuptools.command.setopt (top-level), setuptools.package_index (top-level), setuptools.ssl_support (top-level), setuptools.command.egg_info (top-level), setuptools.command.py36compat (top-level), setuptools.msvc (top-level), 'setuptools._vendor.six.moves' (top-level)
> missing module named setuptools.extern.six.moves.filterfalse - imported by setuptools.extern.six.moves (top-level), setuptools.dist (top-level), setuptools.msvc (top-level)
> missing module named setuptools.extern.six.moves.filter - imported by setuptools.extern.six.moves (top-level), setuptools.dist (top-level), setuptools.ssl_support (top-level), setuptools.command.py36compat (top-level)
> missing module named setuptools.extern.six.moves.map - imported by setuptools.extern.six.moves (top-level), setuptools.dist (top-level), setuptools.command.easy_install (top-level), setuptools.sandbox (top-level), setuptools.package_index (top-level), setuptools.ssl_support (top-level), setuptools.command.egg_info (top-level)
> missing module named setuptools.extern.six - imported by setuptools.extern (top-level), setuptools.monkey (top-level), setuptools.dist (top-level), setuptools.extern.six.moves (top-level), setuptools.py33compat (top-level), setuptools.config (top-level), setuptools.command.easy_install (top-level), setuptools.sandbox (top-level), setuptools.py27compat (top-level), setuptools.package_index (top-level), setuptools.wheel (top-level), setuptools.command.egg_info (top-level), setuptools.command.sdist (top-level), setuptools.command.bdist_egg (top-level), setuptools.unicode_utils (top-level), setuptools.glob (top-level)
> missing module named setuptools.extern.packaging - imported by setuptools.extern (top-level), setuptools.dist (top-level), setuptools.command.egg_info (top-level)
> missing module named 'setuptools._vendor.six.moves' - imported by 'setuptools._vendor.six.moves' (top-level)
> missing module named 'setuptools.extern.packaging.version' - imported by setuptools.msvc (top-level)
> missing module named _manylinux - imported by setuptools.pep425tags (delayed, optional)
> missing module named wincertstore - imported by setuptools.ssl_support (delayed, optional)
> missing module named 'backports.ssl_match_hostname' - imported by setuptools.ssl_support (optional)
> missing module named 'setuptools.extern.six' - imported by setuptools (top-level), setuptools.extension (top-level)
> missing module named cStringIO - imported by cPickle (top-level), cffi.ffiplatform (optional)
> missing module named copy_reg - imported by cPickle (top-level), cStringIO (top-level)
> missing module named cPickle - imported by pycparser.ply.yacc (delayed, optional)
> missing module named cffi._pycparser - imported by cffi (optional), cffi.cparser (optional)
> missing module named Cookie - imported by requests.compat (conditional)
> missing module named cookielib - imported by requests.compat (conditional)
> missing module named urllib2 - imported by requests.compat (conditional)
> missing module named urlparse - imported by requests.compat (conditional)
> missing module named simplejson - imported by requests.compat (optional)
> missing module named backports - imported by urllib3.packages.ssl_match_hostname (optional)
> missing module named Queue - imported by urllib3.util.queue (conditional)
> missing module named brotli - imported by urllib3.util.request (optional), urllib3.response (optional)
> missing module named "'urllib3.packages.six.moves.urllib'.parse" - imported by urllib3.request (top-level), urllib3.poolmanager (top-level)
> runtime module named urllib3.packages.six.moves - imported by http.client (top-level), urllib3.connectionpool (top-level), urllib3.util.response (top-level), 'urllib3.packages.six.moves.urllib' (top-level), urllib3.response (top-level), urllib3.util.queue (top-level)
> missing module named socks - imported by urllib3.contrib.socks (optional)
> missing module named _dummy_threading - imported by dummy_threading (optional)
> missing module named 'typing.io' - imported by importlib.resources (top-level)
> missing module named 'OpenSSL.crypto' - imported by urllib3.contrib.pyopenssl (delayed)
> missing module named OpenSSL - imported by urllib3.contrib.pyopenssl (top-level)
> missing module named posix - imported by os (conditional, optional)
> missing module named resource - imported by posix (top-level)
> `

**Comment by hakanonymos** [comment]
Do you have install python and add python to path ?? When you install python ,do you have choose add to path ?? Test without local or try install module manually without file.bat

**Comment by EMRSoftware** [comment]
> Do you have install python and add python to path ?? When you install python ,do you have choose add to path ?? Test without local or try install module manually without file.bat

I already installed python and added python to path and I installed de modules manually inside the .bat file

**Comment by hakanonymos** [comment]
When i upload this script it was fud ,try to desable your antivirus ,today i will make a new tutorial video how to build that .

**Comment by EMRSoftware** [comment]
> When i upload this script it was fud ,try to desable your antivirus ,today i will make a new tutorial video how to build that .

ı disabled all but its same waiting your solution, thanks

**Comment by EMRSoftware** [comment]
when u release the video, or do you have any solutions for my issue, thanks

**Comment by hakanonymos** [comment]
The probleme is your pyinstaller,open your terminal and run, pyinstaller

**Comment by hakanonymos** [comment]
you can see the video manual installation , the first video removed by youtube,i have upload in facebook

https://www.facebook.com/102313318301415/videos/3262395040481000/

**Comment by EMRSoftware** [comment]
> you can see the video manual installation , the first video removed by youtube,i have upload in facebook
> 
> https://www.facebook.com/102313318301415/videos/3262395040481000/

Thanks for upload, ı fixed it. Nice work btw.
