### ISSUE TITLE
Failed to Execute the script

### ISSUE THREAD

**Issue by YasirAsim** [hakanonymos/steal-chrome-password-all-version#7]
Hi, Thank you very much for this script. 
I'm able to successfully create .exe file of my_email.py file. Everything on CLI works well without any error. But unfortunately after compiling .exe file, When I run it says "Failed to execute script my_email.exe"
Can you please take a look at this matter? 
Looking forward to hearing from you soon. Thanks

**Comment by hakanonymos** [comment]
https://www.facebook.com/102313318301415/videos/3262395040481000/

**Comment by hakanonymos** [comment]
Where is exactly the probleme ?? Tey local.py

https://www.facebook.com/102313318301415/videos/3262395040481000/
